[0.027s] Invoking command in '/home/rosbot/ros2_ws/build/custom_msgs': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/rosbot/ros2_ws/install/my_py_pkg:/home/rosbot/ros2_ws/install/flight_controller_pkg:/home/rosbot/ros2_ws/install/flask_pkg:/home/rosbot/ros2_ws/install/estimator_pkg:/opt/ros/jazzy PS1=(venv) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ VIRTUAL_ENV_PROMPT=(venv) /usr/bin/cmake --build /home/rosbot/ros2_ws/build/custom_msgs -- -j4 -l4
[0.072s] -- Found ament_cmake: 2.5.3 (/opt/ros/jazzy/share/ament_cmake/cmake)
[0.119s] -- Found Python3: /home/rosbot/ros2_ws/venv/bin/python3 (found version "3.12.3") found components: Interpreter 
[0.251s] -- Found rosidl_default_generators: 1.6.0 (/opt/ros/jazzy/share/rosidl_default_generators/cmake)
[0.255s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.299s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.339s] -- Found rosidl_adapter: 4.6.5 (/opt/ros/jazzy/share/rosidl_adapter/cmake)
[0.616s] [31mCMake Error at /opt/ros/jazzy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
[0.616s]   execute_process(/home/rosbot/ros2_ws/venv/bin/python3 -m rosidl_adapter
[0.616s]   --package-name custom_msgs --arguments-file
[0.616s]   /home/rosbot/ros2_ws/build/custom_msgs/rosidl_adapter__arguments__custom_msgs.json
[0.616s]   --output-dir
[0.616s]   /home/rosbot/ros2_ws/build/custom_msgs/rosidl_adapter/custom_msgs
[0.616s]   --output-file
[0.616s]   /home/rosbot/ros2_ws/build/custom_msgs/rosidl_adapter/custom_msgs.idls)
[0.617s]   returned error code 1:
[0.617s] 
[0.617s]   Error processing 'XYZ_Data possition' of 'custom_msgs/EstimatorData':
[0.617s]   ''XYZ_Data' is an invalid message name.  It should have the pattern
[0.617s]   '^[A-Z][A-Za-z0-9]*$''
[0.617s] 
[0.617s]   Traceback (most recent call last):
[0.617s] 
[0.617s]     File "<frozen runpy>", line 198, in _run_module_as_main
[0.617s]     File "<frozen runpy>", line 88, in _run_code
[0.617s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.617s]       sys.exit(main())
[0.617s]                ^^^^^^
[0.617s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/main.py", line 53, in main
[0.618s]       abs_idl_file = convert_to_idl(
[0.618s]                      ^^^^^^^^^^^^^^^
[0.618s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.618s]       return convert_msg_to_idl(
[0.618s]              ^^^^^^^^^^^^^^^^^^^
[0.618s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.618s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.618s]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0.618s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/parser.py", line 521, in parse_message_string
[0.618s]       Type(type_string, context_package_name=pkg_name),
[0.618s]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0.618s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/parser.py", line 278, in __init__
[0.618s]       super(Type, self).__init__(
[0.618s]     File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/parser.py", line 206, in __init__
[0.619s]       raise InvalidResourceName(
[0.619s] 
[0.619s]   rosidl_adapter.parser.InvalidResourceName: 'XYZ_Data' is an invalid message
[0.619s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.619s] 
[0.619s] Call Stack (most recent call first):
[0.619s]   /opt/ros/jazzy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
[0.619s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[0.619s] 
[0.619s] [0m
[0.619s] -- Configuring incomplete, errors occurred!
[0.627s] gmake: *** [Makefile:2165: cmake_check_build_system] Error 1
[0.630s] Invoked command in '/home/rosbot/ros2_ws/build/custom_msgs' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/rosbot/ros2_ws/install/my_py_pkg:/home/rosbot/ros2_ws/install/flight_controller_pkg:/home/rosbot/ros2_ws/install/flask_pkg:/home/rosbot/ros2_ws/install/estimator_pkg:/opt/ros/jazzy PS1=(venv) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ VIRTUAL_ENV_PROMPT=(venv) /usr/bin/cmake --build /home/rosbot/ros2_ws/build/custom_msgs -- -j4 -l4
